#!/bin/bash
#
# ======================================================================

AWSPROFILE="default"
aws ec2 --profile $AWSPROFILE associate-address --instance-id $(cat stage-instance) --public-ip $(cat stage-ip) --allow-reassociation # --dry-run 
