#!/bin/bash
# ======================================================================
AWSPROFILE="default"
# dev
#aws ec2 --profile $AWSPROFILE start-instances --instance-id i-00905802b49e0595d 
# prod 
#aws ec2 --profile $AWSPROFILE start-instances --instance-id i-028587bc01186d8ed 
# stage 
aws ec2 --profile $AWSPROFILE start-instances --instance-id i-0feb3d2170d7d734e 
