#!/usr/bin/bash
#
#i dev-instance, stage-instance, and prod-instance contain instance IDs
# for those instances
#
# ======================================================================

AWSPROFILE="default"
aws ec2 --profile $AWSPROFILE describe-instances --instance-ids $(cat dev-instance) $(cat stage-instance) $(cat prod-instance) |tee instances.json

