#!/bin/bash
#

#



#



#

#
# ======================================================================

AWSPROFILE="default"
# dev
aws ec2 --profile $AWSPROFILE stop-instances --instance-id $(cat dev-instance) 
