#!/bin/bash
# ======================================================================

AWSPROFILE="default"
# dev
aws ec2 --profile $AWSPROFILE start-instances --instance-id $(cat dev-instance) 
# prod 
aws ec2 --profile $AWSPROFILE start-instances --instance-id $(cat prod-instance) 
# stage 
aws ec2 --profile $AWSPROFILE start-instances --instance-id $(cat stage-instance) 
