#!/bin/bash
# ======================================================================

AWSPROFILE="default"
aws ec2 --profile $AWSPROFILE run-instances --image-id ami-c01881b8 --count 1 --instance-type t2.xlarge --key-name heinlein-rsa --security-group-ids sg-6b842a17 --subnet-id subnet-57ddff31 --tag-specifications 'ResourceType=volume,Tags=[{Key=name,Value=samvera-dev},{Key=Administrator,Value=acc@ohsu.edu},{Key=Customer,Value=forero@ohsu.edu}]' # --dry-run 
