#!/usr/bin/bash
# prod-instance contains instance ID
# ======================================================================

AWSPROFILE="default"
aws ec2 --profile $AWSPROFILE start-instances --instance-id $(cat prod-instance) 
