#!/bin/bash
#
#i dev-instance, stage-instance, and prod-instance contain instance IDs
# for those instances
#
# ======================================================================

AWSPROFILE="default"
aws ec2 --profile $AWSPROFILE describe-instances --filters "Name=owner-id,Values=$(cat owners)" |tee instances.json

