#!/bin/bash
#
# catted files contain instance IDs
# ======================================================================

AWSPROFILE="default"
aws ec2 --profile $AWSPROFILE stop-instances --instance-id $(cat stage-instance) 
