#!/bin/bash
#
#i dev-instance, stage-instance, and prod-instance contain instance IDs
# for those instances
#
# ======================================================================

AWSPROFILE="default"
aws ec2 --profile $AWSPROFILE describe-images --owners $(cat owners) |tee images.json
cat images.json |jq '.Images[]' | jq -r '[.ImageId, .Name, .Description] | @tsv'

