#!/bin/bash
# ======================================================================
AMI="$(aws ec2 --profile default describe-images --owners $(cat owners) | jq -r '.Images[] | select(.Name|test("samvera-prod")) | [(.ImageId, .Name, .Description)] | @tsv' | sort -k2 | head -1 | cut -f1)"
COMMAND="aws ec2 --profile default deregister-image --image-id ${AMI}"
#echo ${IMAGEID}
echo ${COMMAND}
