#!/bin/bash
#
# /usr/local/bin/library-archive for libaws.ohsu.edu
#
# copies (via s3 sync) a directory tree to the named BUCKET
# at AWS, encrypting the data at rest using $KEYID. only users
# given access to the key may employ this script.
#
# the underlying s3 bucket has a two-day lifecycle-transition
# policy. files copied up on a Monday will be transitioned to
# AWS Glacier storage on the following Wednesday.
#
# Please contact acc@ohsu.edu for script maintenance.
#
# ======================================================================

AWSPROFILE="default"
#aws --profile $AWSPROFILE s3 cp $1 $BUCKET/$1
# all
#aws ec2 --profile $AWSPROFILE describe-instances 
# dev
#aws ec2 --profile $AWSPROFILE describe-instances --instance-ids i-0017dff820c15f401
# stage
aws ec2 --profile $AWSPROFILE list-users

