#!/usr/bin/bash
#
# ======================================================================

AWSPROFILE="default"
# dev 
aws ec2 --profile $AWSPROFILE associate-address --instance-id $(cat prod-instance) --public-ip $(cat prod-ip) --allow-reassociation # --dry-run 
