#!/usr/bin/bash
#
# /usr/local/bin/library-archive for libaws.ohsu.edu
#
# copies (via s3 sync) a directory tree to the named $BUCKET
# at AWS, encrypting the data at rest using $KEYID. only users
# given access to the key may employ this script.
#
# the underlying s3 bucket has a two-day lifecycle-transition
# policy. files copied up on a Monday will be transitioned to
# AWS Glacier storage on the following Wednesday.
#
# Please contact acc@ohsu.edu for script maintenance.
#
# ======================================================================

# Define destination AWS S3 bucket.
BUCKET="s3://ohsu-library-lt-archive"
# Define AWS customer key used to encrypt data at rest.
KEYID="arn:aws:kms:us-west-2:608317227044:alias/lt-archive"
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"

aws s3 sync /mnt/libnas1/Glacier "s3://ohsu-library-lt-archive" --sse aws:kms --sse-kms-key-id "arn:aws:kms:us-west-2:608317227044:alias/lt-archive" --exclude='*' --include="$1"
