#!/usr/bin/bash
# copies (via s3 sync) a directory tree to the named $BUCKET
# ======================================================================
# Define destination AWS S3 bucket.
BUCKET="s3://ohsu-library-lt-archive"
# Define AWS customer key used to encrypt data at rest.
KEYID="arn:aws:kms:us-west-2:608317227044:alias/lt-archive"
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
aws s3 sync /mnt/libnas1/Glacier "s3://ohsu-library-lt-archive" --sse aws:kms --sse-kms-key-id "arn:aws:kms:us-west-2:608317227044:alias/lt-archive" --exclude='*' --include="$1"
