#!/bin/bash
#
#
#
#
#
# ======================================================================
# Define destination AWS S3 bucket.
PUBLICBUCKET="s3://ohsu-library-public"
PRIVATEBUCKET="s3://ohsu-library-lt-archive"
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
aws --profile $AWSPROFILE s3 cp "$PRIVATEBUCKET/$1" "$PUBLICBUCKET/$1"
