#!/bin/bash
#

#



#



#

#
# ======================================================================

# Define destination AWS S3 bucket.
#BUCKET="s3://ohsu-library-public"
BUCKET="ohsu-library-lt-archive"
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
aws --profile $AWSPROFILE s3api head-object --bucket $BUCKET --key $1
