#!/bin/bash
# copies (via s3 sync) a directory tree to the named $BUCKET
# ======================================================================
# Define destination AWS S3 bucket.
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
echo "aws --profile $AWSPROFILE s3api list-buckets"
aws --profile $AWSPROFILE s3api list-buckets
