#!/bin/bash
#
#
# copies (via s3 sync) a directory tree to the named $BUCKET
#
#
#
# ======================================================================
# Define destination AWS S3 bucket.
#BUCKET="s3://ohsu-library-public"
BUCKET="s3://ohsu-library-lt-archive"
#BUCKET="s3://ohsu-library-bepress"
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
echo "aws --profile $AWSPROFILE s3 ls $BUCKET --recursive --summarize --human-readable"
aws --profile $AWSPROFILE s3 ls $BUCKET --recursive --summarize --human-readable
