#!/bin/bash
#
#
# copies (via s3 sync) a directory tree to the named $BUCKET
#
#
#
# ======================================================================
# Define destination AWS S3 bucket.
BUCKET="ohsu-library-public"
# Define AWS customer key used to encrypt data at rest.
KEYID="arn:aws:kms:us-west-2:608317227044:alias/lt-archive"
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
aws --profile $AWSPROFILE s3api put-object-acl --acl public-read --bucket $BUCKET --key $1 
