#!/bin/bash
#
# /usr/local/bin/library-archive for libaws.ohsu.edu
# ======================================================================

# Define destination AWS S3 bucket.
BUCKET="ohsu-library-lt-archive"

# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
aws --profile $AWSPROFILE s3api put-object-acl --bucket $BUCKET --key $1 --grant-
