#!/bin/bash
#
#
#
#
#
# ======================================================================
# Define destination AWS S3 bucket.
#BUCKET="s3://ohsu-library-public"
BUCKET="s3://ohsu-library-lt-archive"
# Define command-line profile to use in aws CLI operations.
AWSPROFILE="default"
aws --profile $AWSPROFILE s3 cp $1 $BUCKET/$1 
